services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - medialabo-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  patient-service:
    build:
      context: ./medialabo
    container_name: patient-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/MediaLabo
      - SPRING_APPLICATION_JSON={"server":{"port":8080}}
    depends_on:
      - mongo
    networks:
      - medialabo-net

  note-service:
    build:
      context: ./note-service
    container_name: note-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/MediaLabo
      - SPRING_APPLICATION_JSON={"server":{"port":8080}}
    depends_on:
      - mongo
    networks:
      - medialabo-net

  risk-service:
    build:
      context: ./risk-service
    container_name: risk-service
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # ⬇️ Correction: enlever les quotes échappées autour du JSON
      - SPRING_APPLICATION_JSON={"custom":{"api-base-url":"http://api-gateway:8081"}}
    depends_on:
      - patient-service
      - note-service
    networks:
      - medialabo-net

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - patient-service
      - note-service
      - risk-service
    networks:
      - medialabo-net

  front-service:
    build:
      context: ./front-service
    container_name: front-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - 'SPRING_APPLICATION_JSON={"custom":{"api-base-url":"http://api-gateway:8081"},"server":{"port":8080}}'
    depends_on:
      - api-gateway
    networks:
      - medialabo-net

volumes:
  mongo_data:

networks:
  medialabo-net:
    